### ISSUE TITLE
Lots of weird things

### ISSUE THREAD

**Issue by MrWaltz-b14** [El-Qassam/Ooga-Booga-Python-Virus#1]
Why are you working on a prototype for a very simple virus, while it’s good to test it’s certainly possibly to make an efficient one in a single file. You used two, nor is it even functional. And why did you put python in the title?

**Comment by El-Qassam** [comment]
1. I put Python in there because a virus in Py is relatively rare, so flaunting it is key.
2. It’s no longer a prototype, I have tested it.
3. It does its job very well you insolent monkey. Creates files and sticks them to desktop you liar. It has been tested on Rasbpian.

#LYING MONKEY
#NOLIFE
#URVIRUSISBOOTYHOLE,NOTEVENUNIQUE
